# Generated by Django 3.0 on 2023-08-30 06:08

from django.db import migrations


def move_data_from_old_to_new_model_addresses(apps, schema_editor):
    OldModel = apps.get_model("oc_lettings_site", "Address")
    NewModel = apps.get_model("lettings", "Address")

    for old_obj in OldModel.objects.all():
        new_obj = NewModel(
            number=old_obj.number,
            street=old_obj.street,
            city=old_obj.city,
            state=old_obj.state,
            zip_code=old_obj.zip_code,
            country_iso_code=old_obj.country_iso_code,
        )
        new_obj.save()


def move_data_from_old_to_new_model_lettings(apps, schema_editor):
    OldModel = apps.get_model("oc_lettings_site", "Letting")
    NewModel = apps.get_model("lettings", "Letting")

    for old_obj in OldModel.objects.all():
        new_obj = NewModel(
            title=old_obj.title,
            address_id=old_obj.address_id,
        )
        new_obj.save()


class Migration(migrations.Migration):
    dependencies = [
        ("lettings", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(move_data_from_old_to_new_model_lettings),
    ]
